### PR TITLE
fix: typo in documentation

### PR DESCRIPTION
**Pull request by jordijs**

### CODE REVIEW

**Review by FranEnLaNube — APPROVED** [review]
Well done @jordijs, I've reviewed and asked other team members to do it because two approves are needed to be able to merge a PR. 👋

**Review by jordimorillo — APPROVED** [review]

**Comment by jordimorillo** [comment]
I'd like to see more micro-commits like this to solve stupid things that make our eyes to bleed. It demostrate you keep care in our code. Good job.

**Review by toniGitH — APPROVED** [review]
Well observed!!

Suggestion: it might be interesting to replace in these instructions all references where it says **laravel-docker** with: 
~~~
itaprofilesbackend-app 
~~~
to avoid errors when running them, especially for new team members.

Like this:

~~~
docker exec -it <app-container-name> <the-command>

# EXAMPLES:
# To setup the libraries with composer:
docker exec -it itaprofilesbackend-app composer install

# To update libraries with composer: 
docker exec -it itaprofilesbackend-app composer update

# To run the tests with phpunit:
docker exec -it itaprofilesbackend-app ./vendor/bin/phpunit ./tests

# To use php artisan:
docker exec -it itaprofilesbackend-app php artisan ... <whatever...>

# For example, when installing you'll find useful to do:
docker exec -it itaprofilesbackend-app artisan migrate:fresh
docker exec -it itaprofilesbackend-app php artisan db:seed
~~~

**Comment by FranEnLaNube** [comment]
@toniGitH I also think that. You can push those changes to this branch before we merge it. I think everyone will agree with that.

**Comment by jordijs** [comment]
Merging, after adding the suggestions by @toniGitH

**Pull request merged**
