### PR TITLE
Feature/fake-students-endpoint

### PR DESCRIPTION
**Pull request by coxen34**
Add fake route and images

### CODE REVIEW

**Review by FranEnLaNube — APPROVED** [review]
As a feature to just test if we can connect our repo with our FE partners one, I think is fair enough. IDK if @jordimorillo would like to test this, but ATM I Think is ok.
Good and really fast job! 🎉

**Comment by pupadevs** [comment]
Good work, I have tried the test route on local machine and everything is fine. 😸 

I have a suggestion to add to your contribution, instead of launching the student array directly in the routes, you can create a json file in the public folder and store the data in that file. 
Example:
 **return response()->file(public_path('fakeData.json'));**

**Review by pupadevs — COMMENTED** [review]
Good work, I have tested the test route on local machine and everything is fine. 😸 

- I have a suggestion to add to your contribution, instead of throwing the array of students directly in the routes, you can create a json file in the public folder and store the data in that file. 

Example: 
**return response()->file(public_path('fakeData.json'));**

I think it adds more elegibity and if you decide to add more fields or more students, the path file will be very loaded with data that will only be test data.

**Review by AlejandroNPereyra — APPROVED** [review]
Nothing to add! Súper Rosa!

**Comment by coxen34** [comment]
Now the students.json file is located in database/data

**Pull request merged**
