### PR TITLE
Admin Crud #15

### PR DESCRIPTION
**Pull request by elpupas**
### CHANGES:
# IT Profiles API - Admin Controller #15 

This controller manages operations related to administrators in the IT Profiles system.

### Resources for JSON Responses

This controller utilizes Laravel resources to format and present data consistently. Resources provide a convenient and standardized way to transform models or data into JSON responses. This helps in maintaining a clean and organized codebase, as well as ensuring consistent API responses.

### Authentication with Passport

The controller uses the Passport authentication middleware to provide secure access to the API. Passport is a Laravel tool that makes implementing OAuth2 authentication for mobile and single-client applications easier.

### Spatie Role Middleware

Additionally, the controller makes use of the Spatie role middleware to effectively manage user roles. Spatie is a Laravel permissions and roles library that allows for simple and flexible user permission management.

The routes are protected by the `auth:api`, `role`, and `api` middlewares.

## Protected Routes

- [Get All Admins](#get-all-admins)
- [Get Admin Details](#get-admin-details)
- [Update an Administrator](#update-an-administrator)
- [Delete an Admin](#delete-an-admin)

The following routes are protected and require authentication, role authorization, and API access.

---

## Get All Admins

- **URL:** `api/v1/admins`
- **Method:** GET
- **Description:** Get a list of all admins.

---

## Get Admin Details

- **URL:** `api/v1/admins/{id}`
- **Method:** GET
- **Description:** Get the details of a specific administrator.

---

## Update an Administrator

- **URL:** `api/v1/admins/{id}`
- **Method:** PUT
- **Description:** Update the details of a specific administrator.

---

## Delete an Admin

- **URL:** `api/v1/admins/{id}`
- **Method:** DELETE
- **Description:** Delete a specific admin by their ID.

---
# Custom annotations for OpenApi documentation

I have implemented a custom annotation system as commented by Andrea to improve the OpenApi documentation in this Laravel application. Here is a brief summary of the directory structure:

- `app
  - Annotations` (custom annotations directory)
    - OpenApi` (OpenApi Annotations)
      - ControllersAnnotations` (Annotations for controllers)
        - ControllerName` (Controller annotations for the controller ControllerName)
          - ControllerName.php (Annotations file for ControllerName)
      - ModelAnnotations` (Annotations for models)
        - ModelName` (Annotations for ModelName model)
          - ModelName.php` (Annotations file for ModelName)

This structure organizes the annotations for each controller and model in separate folders, making it easy to locate and manage the annotation files.

Feel free to explore the annotations in their respective folders for more details on how they are used in the application.

Note: Be sure to follow the naming conventions and syntax specified in the annotations for accurate documentation generation.

---
# UserRequest and DniRule

## UserRequest

The `UserRequest` is a custom form request class used for validating user input before processing it. It includes the following validation rules:

- `name`: Required. Should be a string containing only alphabetical characters. Use the following regular expression (regexp) to enforce this restriction: `/^[^0-9\/?|\\)(*&%$#@!{}\[\]:;_="<>]+$/`.
- `surname`: Required. Should be a string containing only alphabetical characters. Use the following regular expression (regexp) to enforce this restriction: `/^[^0-9\/?|\\)(*&%$#@!{}\[\]:;_="<>]+$/`.
- `dni`: Required, unique, and must pass custom DNI/NIE validation.
- `email`: Required, string, valid email format, and must be unique.
- `password`: Required, string, minimum length of 8 characters.

## DniRule Validation Rule

The `DniRule` is a custom validation rule implemented in the IT Profiles API. It serves to validate Spanish tax identification numbers (NIF) and foreigner identification numbers (NIE) for accuracy and legitimacy.

### How DniRule Works

This validation rule employs a combination of regular expressions and mathematical calculations to verify the validity of the provided identification number.

### Validating NIF

- The `isValidNif` function meticulously checks the validity of an NIF.
- It relies on the regular expression `/^[0-9]{8}[A-Z]$/i` for precise validation.
- The function cross-ensures that the control digit corresponds with the calculated result.

### Validating NIE

- The `isValidNie` function performs a thorough validation of an NIE.
- It utilizes the regular expression `/^[KLMXYZ][0-9]{7}[A-Z]$/i` to verify its authenticity.
- By applying a series of transformations and calculations, the function ensures the document's legitimacy.

These validation methods ensure that all tax identification numbers, whether NIF or NIE, are accurately validated within the IT Profiles API.

Note: The regular expressions used for validating `name` and `surname` in the `UserRequest` prevent the insertion of special characters.

### CODE REVIEW

**Comment by j-obiols** [comment]
Hola Peterson, muy buen trabajo, felicidades!!   Te comento tres cosas, pero son muy menores, o sea que para mi, ya se puede hacer "merge".

1 - Cuando creas  un Admin lo haces así:

 Admin::create([
                'user_id' => $user->id,
            ]);

Hay otra manera, a través de la relación uno a uno:

**$user->admin()->create( [   _aquí iría asignación de atributos, pero en tu caso no tienes_ ]);**  

y Laravel **ya establece automáticamente el user_id**, no hace falta decírselo. No sé si lo has probado, yo lo he hecho de esta segunda manera.

2 - Lo que hago también cuando hay una transacción, es poner un validador a continuación: si la transacción no se ha podido realizar, lanzo un mensaje de error...

3 - En la rule de validación dni,  diría que la respuesta tendría que estar entre corchetes para translate, como estuvimos comentando ayer...Puedes hacer una prueba cambiando momentáneamente el idioma predeterminado de ca a es, a ver si llega en castellano o no...

public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        if (!($this->isValidNif(strtoupper($value)) || $this->isValidNie(strtoupper($value)))) {
            $fail(**__('No és un :Attribute vàlid')**);
        }
    }

4 - Lo de añadir la traducción de los attributes de user que no estén en el ca/validation.php, ya lo he hecho yo. Solo faltaba añadir el surname.

**Comment by elpupas** [comment]
> Hola Peterson, muy buen trabajo, felicidades!!   Te comento tres cosas, pero son muy menores, o sea que para mi, ya se puede hacer "merge".
> 
> 1 - Cuando creas  un Admin lo haces así:
> 
>  Admin::create([
>                 'user_id' => $user->id,
>             ]);
> 
> Hay otra manera, a través de la relación uno a uno:
> 
> **$user->admin()->create( [   _aquí iría asignación de atributos, pero en tu caso no tienes_ ]);**  
> 
> y Laravel **ya establece automáticamente el user_id**, no hace falta decírselo. No sé si lo has probado, yo lo he hecho de esta segunda manera.
> 
> 2 - Lo que hago también cuando hay una transacción, es poner un validador a continuación: si la transacción no se ha podido realizar, lanzo un mensaje de error...
> 
> 3 - En la rule de validación dni,  diría que la respuesta tendría que estar entre corchetes para translate, como estuvimos comentando ayer...Puedes hacer una prueba cambiando momentáneamente el idioma predeterminado de ca a es, a ver si llega en castellano o no...
> 
> public function validate(string $attribute, mixed $value, Closure $fail): void
>     {
>         if (!($this->isValidNif(strtoupper($value)) || $this->isValidNie(strtoupper($value)))) {
>             $fail(**__('No és un :Attribute vàlid')**);
>         }
>     }
> 
> 4 - Lo de añadir la traducción de los attributes de user que no estén en el ca/validation.php, ya lo he hecho yo. Solo faltaba añadir el surname. 


Los 4 puntos mencionado por @j-obiols ya están solventados

**Comment by CloudSalander** [comment]
Hi, Pupa!
- This is a main issue, not specifically from your feature, BUT, maybe we should indicate in Swagger a sample of a complete api/call, explaining "api/v1".
- How nice to see that you used Transactions!
- Maybe we should discuss if is appropiate to left admins post endpoint public. Maybe we, as app maintainers, we have to provide a created admin and let this admin create new admins, and only this admin.

**Comment by CloudSalander** [comment]
Pupa, maybe we don't need actually to put in EVERY single endpoint the complete path, just a sample on the top part of the swagger page. The endpoints parts its ok.

Thanks :)

**Pull request merged**
